name: fsm2_viewer
version: 3.0.0
description: A viewer for svg state machine graphs generate by the FSM2 project.
repository: https://github.com/bsutton/fsm2_viewer
environment: 
  sdk: '>=2.12.0-0 <3.0.0'
dependencies: 
  pluto_menu_bar: ^1.0.0-0
  file_picker_cross: ^4.2.6
  file_picker: ^3.0.0-0
  flutter_svg: ^0.20.0-0
  fsm2: ^2.0.0
  path: ^1.0.0
  synchronized: ^3.0.0
  cupertino_icons: ^1.0.1
  flutter_riverpod: ^0.13.0-0
  flutter: 
    sdk: flutter
  flutter_web_plugins: 
    sdk: flutter
dev_dependencies: 
  integration_test: ^1.0.2+2
  flutter_test: 
    sdk: flutter
dependency_overrides: 
  archive: ^3.0.0
  meta: ^1.3.0-0
  collection: ^1.15.0-0
  typed_data: ^1.3.0-0
  ffi: ^0.1.3
  path: ^1.8.0
  args: ^2.0.0
  yaml: ^3.0.0
  string_scanner: ^1.1.0
  source_span: ^1.8.0
  charcode: ^1.2.0
  term_glyph: ^1.2.0
  pub_semver: ^2.0.0
  glob: ^2.0.0
  file: ^6.0.0
  async: 2.5.0
  pedantic: ^1.10.0
  crypto: ^3.0.0
  logging: ^1.0.0
  matcher: ^0.12.10
  stack_trace: ^1.10.0
flutter: 
  uses-material-design: true
